### ISSUE TITLE
Invalid Redirect URI

### ISSUE THREAD

**Issue by wvance** [codebender/omniauth-fitbit-oauth2#4]
I am receiving an error after requesting authorization: 

Developer information: invalid_request - Invalid redirect_uri parameter value

After reading the Fitbit api docs, it says a required field is the redirect_ui?

My code is as follows: 

config.omniauth :fitbit_oauth2, ENV["fitbit_client_id"], ENV["fitbit_secret"],
    scope: 'activity heartrate location nutrition profile sleep settings social weight', 
    redirect_uri: 'http://lvh.me:3000'

My callback url on Fitbit is also: http://lvh.me:3000

Any suggestions? :D

**Comment by codebender** [comment]
@wvance, Do you happen to have multiple callback URIs? This parameter is optional if you only have one callback url.  So the quick fix for you might be to just remove that `redirect_uri` from your config.  

```
Optional, if you have only specified one callback URI for your application in the settings on dev.fitbit.com, otherwise required. See Callback URIs below.
```

I'll look further into passing the call `redirect_uri`, perhaps there is a bug/problem there.

**Comment by wvance** [comment]
I looked into the API and you are correct it is optional, however after looking at my fitibt app callback, it only has one 'Callback URL' which is "http://lvh.me:3000/". This is also the page of which I am requesting authorization. 
I have removed the 'redirect_uri' from my config file, however the error was still the same. 
Thanks for the help!

**Comment by codebender** [comment]
@wvance Have you tried reproducing this with `localhost:<port>` as the applications callback uri? Or have you tried to reproduce this with the example sinatra app in the /example directory of the gem?

I haven't been able to reproduce your issue locally

I did see this older reddit saying that an invalid client id, would cause a `invalid redirect_uri` error.
https://www.reddit.com/r/redditdev/comments/17ka6l/oauth_invalid_redirect_uri_parameter/ 
Perhaps, double check your ENV["fitbit_client_id"] and ENV["fitbit_secret"]

make sure you are using the fitbit client id labeled `OAuth 2.0 Client ID`

**Comment by wvance** [comment]
So after looking over everything again heres what my url looks like (replaced x with keys), but do you see anything wrong with the request URL? 

https://www.fitbit.com/oauth2/authorize?response_type=code&client_id=xxxxxx&redirect_uri=http%3A%2F%2Flvh.me%3A3000%2Fusers%2Fauth%2Ffitbit_oauth2%2Fcallback&state=xxxxxxxxxxxxxxxxxxxxxxxxxxx&scope=activity+heartrate+location+nutrition+profile+sleep+settings+social+weight

Similarly my callback in Fitbit is "http://lvh.me:3000/". I tried with your sinatra app and didn't have any issues, however in my Rails app I am still having the same problem :/ I have checked and I am passing in the right variables and everything should be matching up AHHH :P 

Thanks for your help. Ill keep looking over things and check if others are having other problems with the Fitbit api.

**Comment by codebender** [comment]
@wvance I think your callback url should be set to `http://lvh.me:3000/auth/fitbit_oauth2/callback` instead of just `http://lvh.me:3000/`

**Comment by wvance** [comment]
@codebender Thank you for you help! Gem works perfect :D I needed to set my callback url on the fitbit website to be 'http://lvh.me:3000/users/auth/fitbit_oauth2/callback'. 

If anyone else has an issue, I used 'http://meyerweb.com/eric/tools/dencoder/' to view the requested url and then fit the callback appropriately. 

Thanks for all your help!
