### ISSUE TITLE
Complete examples

### ISSUE THREAD

**Issue by rmccown** [codebender/omniauth-fitbit-oauth2#5]
Looking for an example of the 'next step', i.e. theh POST to https://api.fitbit.com/oauth2/token after the first round trip.

**Comment by codebender** [comment]
Hi @rmccown,

This stackoverflow link might be helpful if you are looking for more info about the omniauth refresh token flow. http://stackoverflow.com/questions/21707734/refresh-token-using-omniauth-oauth2-in-rails-application

**Comment by curatingbits** [comment]
@codebender 
I think what @rmccown was referring to is after you successfully get back the "code" from the first example request, how do you initiate the Access Token Request with the code using omniauth-fitbit-oauth2? I'm currently trying to figure this out. I see you have the token_ur in the omnioauth strategy. Whenever you get time maybe you could show me the light? Thank you in advanced!

**Comment by codebender** [comment]
@drobsokc,

It sounds like you might be making a lot of the OAuth2 calls by hand, but all the magic is done by [omniauth-oauth2](https://github.com/intridea/omniauth-oauth2).  It does all the handshaking. Take a looks at the [example sinatra app](https://github.com/codebender/omniauth-fitbit-oauth2/blob/master/example/config.ru) 

To run the example app: 
- register a fitbit app at dev.fitbit.com
- set the Callback URL - `http://localhost:9292/auth/fitbit_oauth2/callback`
- clone the repo - `git@github.com:codebender/omniauth-fitbit-oauth2.git`
- change to the example sinatra app directory - `cd omniauth-fitbit-oauth2/example`
- run the app - `FITBIT_CLIENT_ID=<Your Fitbit OAuth 2.0 Client ID> FITBIT_CLIENT_SECRET=<Your Fitbit Client (Consumer) Secret> rackup`

For that example, visiting the uri `http://localhost:9292/` will bring the user to the fitbit login prompt, after logging in you will be redirected back to the url specified as the dev.fitbit.com Callback URL. In the example app that matches the path `/auth/:provider/callback`. At this point the full OAuth2 handshank is complete. You have the all important `token` to start making calls to the fitbit API for user data.

Does that help?

**Comment by curatingbits** [comment]
@codebender 
Thank you for getting back to me! I did indeed fire up your sinatra example app and was able to get everything back from the request parameter like you described. Although it's not like that in my rails app? 

All I have done is added the below code to the omniauth.rb file. I do have  your gem in my Gemfile and done a bundle install. 

```
Rails.application.config.middleware.use OmniAuth::Builder do
 provider :fitbit_oauth2, 'client_id', 'secret',
       :scope => 'profile activity', :expires_in => '2592000'
end  
```

created a route

```
get 'auth/fitbit_oauth2/callback' => 'api#receive'
```

My callback URL is good in my dev.fitbit.com profile. And configured my controller:

```
def receive
  render json: params
end
```

And the only thing I get back in my rails app is this json string:

```
    {"state":"c9933580ffb06ad0a9a67305d9568ed7ee46","code":"bf8f41deebfd4bb9d653ee0","controller":"api","action":"receive"}
```

From the looks of your sinatra example and your gem it should be just that easy! No need for extra oauth calls by hand. Any ideas what I need to do with my rails app to get the same callback with the token and the user data that you get in your Sinatra app? Thank you!

**Comment by curatingbits** [comment]
Alright, so I was rendering the params and not the request.env. Everything I need is inside the request. I just changed my controller to look like below for now so I can see what is inside the request and the string looks more like your example Sinatra app. Thank you again for your reply. Cheers! 

```
def receive
@request = request.env['omniauth.auth']
render json: @request.to_json
end 
```

**Comment by codebender** [comment]
@drobsokc cheers! I'll add a Rails example app to help out everyone.
