### ISSUE TITLE
does this code work?

### ISSUE THREAD

**Issue by dsjoerg** [codebender/omniauth-fitbit-oauth2#6]
hi, i'm trying to find a working oauth2 codebase for fitbit.  does this codebase work for you?   are you doing the refresh-token thing?   thanks in advance!

**Comment by codebender** [comment]
@dsjoerg Yes this code works 😸 Have you tried the example sinatra app included in the repo? https://github.com/codebender/omniauth-fitbit-oauth2/tree/master/example

The refresh token is returned in the response under `credentials`: https://github.com/intridea/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L41

**Comment by dsjoerg** [comment]
Thanks!  If I'm reading it right, it looks like this code will receive the refresh_token, but does not give an example of actually using the refresh_token to do a refresh.

Anyway thanks for the response and the code! <3

**Comment by codebender** [comment]
@dsjoerg, check out this discussion about refreshing tokens: http://stackoverflow.com/a/21879758 😸
